language: python
os:
  - linux
  - osx
python:
  - "3.10-dev"
  - "3.9-dev"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
script:
  - pip install .[test] || true
  - python setup.py install # todo: pip install fails on 3.10
  - python run_tests.py
